# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  pull_request:
    branches: [ "juri" ]

jobs:
  build:
    runs-on: macos-14

    steps:
    # ê°€ìƒ ë¨¸ì‹ ì— ì²´í¬ì•„ì›ƒ(clone)
    - name: âœ… Checkout
      uses: actions/checkout@v4
      
    # Xcode Version ì„¤ì •  
    - name: ğŸ› ï¸ Setting Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
    
    # Config ì„¤ì •
    - name: ğŸ› ï¸ Setting Config
      run: |
        mkdir -p Spoony-iOS/Config
        echo "${CONFIG}" | base64 --decode > Spoony-iOS/Config/Config.swift
        echo "KAKAO_APP_KEY = ${KAKAO_APP_KEY}" > Spoony-iOS/Config/Config.xcconfig
      env:
        CONFIG: ${{ secrets.CONFIG }}
        KAKAO_APP_KEY: ${{ secrets.KAKAO_APP_KEY }}

    # ë¹Œë“œ í…ŒìŠ¤íŠ¸
    - name: âœ… Build with xcodebuild
      run: |
        # ì‚¬ìš© ê°€ëŠ¥í•œ iPhone ì‹œë®¬ë ˆì´í„° ì¤‘ ì²« ë²ˆì§¸ ì„ íƒ
        DEVICE_NAME=$(xcrun simctl list devices available | grep "iPhone" | head -n 1 | awk -F '(' '{print $1}' | sed 's/[[:space:]]*$//')

        echo "Using Simulator: $DEVICE_NAME"

        set -o pipefail

        xcodebuild \
        -project Spoony-iOS/Spoony.xcodeproj \
        -scheme Spoony-iOS \
        -sdk iphonesimulator \
        -destination "platform=iOS Simulator,name=${DEVICE_NAME}" \
        clean build | xcpretty
